import type { TelegramFile } from '../types';

const API_BASE = 'https://api.telegram.org';

/** Every Telegram call is capped: waitUntil's margin is 30 s in total. */
const API_TIMEOUT_MS = 8_000;
const DEFAULT_DOWNLOAD_TIMEOUT_MS = 10_000;

export type ChatAction = 'typing' | 'upload_voice' | 'record_voice';

export interface InlineKeyboardButton {
  text: string;
  callback_data: string;
}

export interface SendMessageOptions {
  replyToMessageId?: number;
  inlineKeyboard?: InlineKeyboardButton[][];
}

export class TelegramError extends Error {
  constructor(
    readonly method: string,
    readonly errorCode: number | undefined,
    description: string,
  ) {
    super(`Telegram ${method} falló (${errorCode ?? 'sin código'}): ${description}`);
    this.name = 'TelegramError';
  }
}

interface TelegramApiResponse<T> {
  ok: boolean;
  result?: T;
  error_code?: number;
  description?: string;
}

export class TelegramClient {
  constructor(private readonly token: string) {}

  private async call<T>(
    method: string,
    payload: Record<string, unknown>,
    timeoutMs = API_TIMEOUT_MS,
  ): Promise<T> {
    const response = await fetch(`${API_BASE}/bot${this.token}/${method}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
      // Without this, one hung call eats waitUntil's whole margin on its own.
      signal: AbortSignal.timeout(Math.max(1_000, timeoutMs)),
    });

    const body = (await response.json()) as TelegramApiResponse<T>;
    if (!body.ok || body.result === undefined) {
      throw new TelegramError(method, body.error_code, body.description ?? 'sin descripción');
    }
    return body.result;
  }

  /**
   * Sends plain text, with no `parse_mode`.
   *
   * Deliberate: MarkdownV2 requires escaping a long list of characters, and one escaping
   * slip returns a 400 that drops the entire message. Once the content is generated by
   * the LLM (Phase 1) that risk is constant, so rich formatting will arrive with an
   * escaper of our own that has been tested, and not before.
   */
  async sendMessage(chatId: number, text: string, options: SendMessageOptions = {}) {
    const payload: Record<string, unknown> = {
      chat_id: chatId,
      text: truncate(text),
    };
    if (options.replyToMessageId !== undefined) {
      payload['reply_to_message_id'] = options.replyToMessageId;
    }
    if (options.inlineKeyboard) {
      payload['reply_markup'] = { inline_keyboard: options.inlineKeyboard };
    }
    return this.call<unknown>('sendMessage', payload);
  }

  /** Shows "typing…". It expires after 5 s or when the message is sent. */
  async sendChatAction(chatId: number, action: ChatAction = 'typing') {
    return this.call<boolean>('sendChatAction', { chat_id: chatId, action });
  }

  async answerCallbackQuery(callbackQueryId: string, text?: string) {
    const payload: Record<string, unknown> = { callback_query_id: callbackQueryId };
    if (text) payload['text'] = text;
    return this.call<boolean>('answerCallbackQuery', payload);
  }

  /** Step 1 for downloading audio (Phase 3): resolves the file_path. */
  async getFile(fileId: string, timeoutMs?: number): Promise<TelegramFile> {
    return this.call<TelegramFile>('getFile', { file_id: fileId }, timeoutMs);
  }

  fileUrl(filePath: string): string {
    return `${API_BASE}/file/bot${this.token}/${filePath}`;
  }

  /**
   * Resolves the file_id and downloads the content. Used for voice notes.
   *
   * `timeoutMs` caps both steps together, not each one. `getFile` used to spend its own
   * 8 s outside the budget, so a download that was "within cap" could take 23 s of the
   * message's 27 and leave the model no time to answer.
   */
  async downloadFile(fileId: string, timeoutMs = DEFAULT_DOWNLOAD_TIMEOUT_MS): Promise<ArrayBuffer> {
    const total = Math.max(1_000, timeoutMs);
    const startedAt = Date.now();

    const file = await this.getFile(fileId, total);
    if (!file.file_path) {
      throw new TelegramError('getFile', undefined, 'la respuesta no traía file_path');
    }

    const response = await fetch(this.fileUrl(file.file_path), {
      signal: AbortSignal.timeout(Math.max(1_000, total - (Date.now() - startedAt))),
    });
    if (!response.ok) {
      throw new TelegramError('downloadFile', response.status, 'no se pudo descargar el fichero');
    }
    return response.arrayBuffer();
  }
}

/** The Bot API's download cap. Beyond it, getFile fails. */
export const MAX_DOWNLOAD_BYTES = 20 * 1024 * 1024;

/**
 * Whether the abort was about time or about something else.
 *
 * `AbortSignal.timeout()` throws a `DOMException` with `name === 'TimeoutError'`, and
 * depending on the runtime it arrives as `AbortError`. The distinction decides what to
 * do: a timeout gets retried, a 400 from Telegram does not.
 */
export function isTimeout(error: unknown): boolean {
  return error instanceof Error && (error.name === 'TimeoutError' || error.name === 'AbortError');
}

/** Telegram rejects messages longer than 4096 characters. */
const MAX_MESSAGE_LENGTH = 4096;

function truncate(text: string): string {
  const trimmed = text.trim();
  if (trimmed.length === 0) return '(respuesta vacía)';
  if (trimmed.length <= MAX_MESSAGE_LENGTH) return trimmed;
  return `${trimmed.slice(0, MAX_MESSAGE_LENGTH - 1)}…`;
}
